interface Resources {
  "de": {
    "Auth": {
      "connecting": "Verbinden...",
      "connecting_description": "Erstelle deine sichere Sitzung.",
      "error_description": "Authentifizierung mit Google fehlgeschlagen. Bitte versuche es erneut.",
      "error_title": "Verbindungsfehler",
      "google_button": "Mit Google anmelden",
      "login_error": "Anmeldung konnte nicht gestartet werden.",
      "login_subtitle": "Intelligente Finanzkontrolle",
      "login_title": "Buckify",
      "redirecting": "Weiterleitung...",
      "retry": "Versuchen",
      "session_error": "Sitzungsfehler",
      "success_toast": "Anmeldung erfolgreich!"
    },
    "Common": {
      "close": "Schließen",
      "firebase_admin_env_error": "Kritischer Fehler: Firebase Admin Umgebungsvariablen nicht gefunden. Überprüfen Sie Ihre .env.local",
      "logo_title": "Buckify Logo",
      "select_month": "Monat auswählen"
    },
    "Navigation": {
      "add_category": "Neue Kategorie",
      "add_expense": "Neue Ausgabe",
      "cards": "Karten",
      "home": "Startseite",
      "profile": "Profil",
      "read_with_ai": "Mit KI lesen",
      "stats": "Statistiken"
    },
    "Transactions": {
      "add_expense": "Ausgabe hinzufügen",
      "amount": "Betrag (€)",
      "amount_min": "Der Betrag muss größer als 0 sein.",
      "amount_placeholder": "0.00",
      "available": "verfügbar",
      "budget": "Budget",
      "categories": {
        "casa": "Haus",
        "mercado": "Markt",
        "outros": "Andere",
        "restaurantes": "Restaurants & Freizeit",
        "saude": "Gesundheit & Pflege",
        "transporte": "Transport"
      },
      "category": "Kategorie",
      "click_to_upload": "Zum Hochladen klicken",
      "currency_symbol": "€",
      "date": "Datum",
      "date_required": "Das Datum ist erforderlich.",
      "description": "Beschreibung",
      "description_min_length": "Die Beschreibung muss mindestens 2 Zeichen haben.",
      "error_parsing_statement": "Fehler beim Analysieren der Abrechnung",
      "error_saving": "Fehler beim Speichern: {message}",
      "error_saving_transactions": "Fehler beim Speichern der Transaktionen",
      "example_dinner": "Bsp: Abendessen auswärts",
      "expense_added_success": "Ausgabe erfolgreich hinzugefügt!",
      "file_too_large": "Datei zu groß (Max 4MB)",
      "hidden_categories": "+ {count} andere Kategorien in den Schatten verborgen...",
      "logout": "Abmelden",
      "month_summary": "Monatsübersicht",
      "new_expense": "Neue Ausgabe",
      "reading_transactions": "Transaktionen werden gelesen...",
      "remaining": "Verbleibend",
      "remaining_label": "Verbleibend:",
      "saving": "Speichern...",
      "select": "Auswählen",
      "select_category": "Wähle eine Kategorie.",
      "session_error_reload": "Sitzungsfehler. Seite neu laden.",
      "spent": "ausgegeben",
      "supported_formats": "PDF oder Bild (JPG, PNG)",
      "total_spent": "Gesamt ausgegeben",
      "transactions_found": "{count} Transaktionen gefunden!"
    }
  },
  "en": {
    "Auth": {
      "connecting": "Connecting...",
      "connecting_description": "Creating your secure session.",
      "error_description": "Unable to authenticate with Google. Please try again.",
      "error_title": "Connection Error",
      "google_button": "Sign in with Google",
      "login_error": "Unable to start login.",
      "login_subtitle": "Smart financial control",
      "login_title": "Buckify",
      "redirecting": "Redirecting...",
      "retry": "Try",
      "session_error": "Session failure",
      "success_toast": "Login successful!"
    },
    "Common": {
      "close": "Close",
      "firebase_admin_env_error": "Critical Error: Firebase Admin environment variables not found. Check your .env.local",
      "logo_title": "Buckify Logo",
      "select_month": "Select Month"
    },
    "Navigation": {
      "add_category": "New Category",
      "add_expense": "New Expense",
      "cards": "Cards",
      "home": "Home",
      "profile": "Profile",
      "read_with_ai": "Read with AI",
      "stats": "Stats"
    },
    "Transactions": {
      "add_expense": "Add Expense",
      "amount": "Amount (€)",
      "amount_min": "The amount must be greater than 0.",
      "amount_placeholder": "0.00",
      "available": "avail.",
      "back": "Back",
      "budget": "Budget",
      "cancel": "Cancel",
      "categories": {
        "casa": "Home",
        "mercado": "Market",
        "outros": "Others",
        "restaurantes": "Restaurants & Leisure",
        "saude": "Health & Care",
        "transporte": "Transport"
      },
      "category": "Category",
      "click_to_upload": "Click to upload",
      "confirm_import": "Confirm Import",
      "currency_symbol": "€",
      "date": "Date",
      "date_required": "The date is required.",
      "description": "Description",
      "description_min_length": "The description must have at least 2 characters.",
      "duplicate_description": "There is already an expense with this date and amount.",
      "error_parsing_statement": "Error parsing statement",
      "error_saving": "Error saving: {message}",
      "error_saving_transactions": "Error saving transactions",
      "example_dinner": "Ex: Dinner out",
      "expense_added_success": "Expense added successfully!",
      "expenses_categorized": "Your expenses will be categorized automatically.",
      "expenses_found": "{count} expenses found",
      "file_too_large": "File too large (Max 4MB)",
      "hidden_categories": "+ {count} other categories hidden in the shadows...",
      "import_title": "Import Statement with AI",
      "logout": "Logout",
      "month_summary": "Month Summary",
      "new_expense": "New Expense",
      "others": "Others",
      "possible_duplicate": "Possible duplicate found!",
      "reading_transactions": "Reading transactions...",
      "remaining": "Remaining",
      "remaining_label": "Remaining:",
      "saving": "Saving...",
      "select": "Select",
      "select_category": "Select a category.",
      "send_image_pdf": "Send an image or PDF.",
      "session_error_reload": "Session error. Reload the page.",
      "spent": "spent",
      "supported_formats": "PDF or Image (JPG, PNG)",
      "total_spent": "Total Spent",
      "transactions_found": "{count} transactions found!"
    }
  },
  "es": {
    "Auth": {
      "connecting": "Conectando...",
      "connecting_description": "Creando tu sesión segura.",
      "error_description": "No se pudo autenticar con Google. Inténtalo de nuevo.",
      "error_title": "Error de conexión",
      "google_button": "Iniciar sesión con Google",
      "login_error": "No se pudo iniciar el inicio de sesión.",
      "login_subtitle": "Control financiero inteligente",
      "login_title": "Buckify",
      "redirecting": "Redirigiendo...",
      "retry": "Intentar",
      "session_error": "Falla en la sesión",
      "success_toast": "¡Inicio de sesión exitoso!"
    },
    "Common": {
      "close": "Cerrar",
      "firebase_admin_env_error": "Error Crítico: Variables de entorno de Firebase Admin no encontradas. Verifique su .env.local",
      "logo_title": "Logo Buckify",
      "select_month": "Seleccionar Mes"
    },
    "Navigation": {
      "add_category": "Nueva Categoría",
      "add_expense": "Nuevo Gasto",
      "cards": "Tarjetas",
      "home": "Inicio",
      "profile": "Perfil",
      "read_with_ai": "Leer con IA",
      "stats": "Estadísticas"
    },
    "Transactions": {
      "add_expense": "Agregar Gasto",
      "amount": "Monto (€)",
      "amount_min": "El monto debe ser mayor que 0.",
      "amount_placeholder": "0.00",
      "available": "disp.",
      "budget": "Presupuesto",
      "categories": {
        "casa": "Casa",
        "mercado": "Mercado",
        "outros": "Otros",
        "restaurantes": "Restaurantes y Ocio",
        "saude": "Salud y Cuidado",
        "transporte": "Transporte"
      },
      "category": "Categoría",
      "click_to_upload": "Haz clic para subir",
      "currency_symbol": "€",
      "date": "Fecha",
      "date_required": "La fecha es obligatoria.",
      "description": "Descripción",
      "description_min_length": "La descripción debe tener al menos 2 caracteres.",
      "error_parsing_statement": "Error al analizar el extracto",
      "error_saving": "Error al guardar: {message}",
      "error_saving_transactions": "Error al guardar transacciones",
      "example_dinner": "Ej: Cena fuera",
      "expense_added_success": "¡Gasto agregado exitosamente!",
      "file_too_large": "Archivo demasiado grande (Máx 4MB)",
      "hidden_categories": "+ {count} otras categorías ocultas en las sombras...",
      "logout": "Cerrar sesión",
      "month_summary": "Resumen del Mes",
      "new_expense": "Nuevo Gasto",
      "reading_transactions": "Leyendo transacciones...",
      "remaining": "Restante",
      "remaining_label": "Restante:",
      "saving": "Guardando...",
      "select": "Seleccionar",
      "select_category": "Selecciona una categoría.",
      "session_error_reload": "Error de sesión. Recarga la página.",
      "spent": "gastado",
      "supported_formats": "PDF o Imagen (JPG, PNG)",
      "total_spent": "Total Gastado",
      "transactions_found": "¡{count} transacciones encontradas!"
    }
  },
  "fr": {
    "Auth": {
      "connecting": "Connexion...",
      "connecting_description": "Création de votre session sécurisée.",
      "error_description": "Impossible de s'authentifier avec Google. Veuillez réessayer.",
      "error_title": "Erreur de connexion",
      "google_button": "Se connecter avec Google",
      "login_error": "Impossible de démarrer la connexion.",
      "login_subtitle": "Contrôle financier intelligent",
      "login_title": "Buckify",
      "redirecting": "Redirection...",
      "retry": "Réessayer",
      "session_error": "Échec de la session",
      "success_toast": "Connexion réussie !"
    },
    "Common": {
      "close": "Fermer",
      "firebase_admin_env_error": "Erreur Critique : Variables d'environnement Firebase Admin introuvables. Vérifiez votre .env.local",
      "logo_title": "Logo Buckify",
      "select_month": "Sélectionner un mois"
    },
    "Navigation": {
      "add_category": "Nouvelle catégorie",
      "add_expense": "Nouvelle dépense",
      "cards": "Cartes",
      "home": "Accueil",
      "profile": "Profil",
      "read_with_ai": "Lire avec IA",
      "stats": "Statistiques"
    },
    "Transactions": {
      "add_expense": "Ajouter une dépense",
      "amount": "Montant (€)",
      "amount_min": "Le montant doit être supérieur à 0.",
      "amount_placeholder": "0.00",
      "available": "disponible",
      "budget": "Budget",
      "categories": {
        "casa": "Maison",
        "mercado": "Marché",
        "outros": "Autres",
        "restaurantes": "Restaurants & Loisirs",
        "saude": "Santé & Soins",
        "transporte": "Transport"
      },
      "category": "Catégorie",
      "click_to_upload": "Cliquez pour télécharger",
      "currency_symbol": "€",
      "date": "Date",
      "date_required": "La date est requise.",
      "description": "Description",
      "description_min_length": "La description doit avoir au moins 2 caractères.",
      "error_parsing_statement": "Erreur lors de l'analyse du relevé",
      "error_saving": "Erreur lors de la sauvegarde : {message}",
      "error_saving_transactions": "Erreur lors de la sauvegarde des transactions",
      "example_dinner": "Ex: Dîner dehors",
      "expense_added_success": "Dépense ajoutée avec succès !",
      "file_too_large": "Fichier trop volumineux (Max 4MB)",
      "hidden_categories": "+ {count} autres catégories cachées dans les ombres...",
      "logout": "Déconnexion",
      "month_summary": "Résumé du mois",
      "new_expense": "Nouvelle dépense",
      "reading_transactions": "Lecture des transactions...",
      "remaining": "Restant",
      "remaining_label": "Restant :",
      "saving": "Sauvegarde...",
      "select": "Sélectionner",
      "select_category": "Sélectionnez une catégorie.",
      "session_error_reload": "Erreur de session. Rechargez la page.",
      "spent": "dépensé",
      "supported_formats": "PDF ou Image (JPG, PNG)",
      "total_spent": "Total dépensé",
      "transactions_found": "{count} transactions trouvées !"
    }
  },
  "pt": {
    "Auth": {
      "connecting": "Conectando...",
      "connecting_description": "Criando sua sessão segura.",
      "error_description": "Não foi possível autenticar com o Google. Tente novamente.",
      "error_title": "Erro ao conectar",
      "google_button": "Entrar com Google",
      "login_error": "Não foi possível iniciar o login.",
      "login_subtitle": "Controle financeiro inteligente",
      "login_title": "Buckify",
      "redirecting": "Redirecionando...",
      "retry": "Tentar",
      "session_error": "Falha na sessão",
      "success_toast": "Login realizado!"
    },
    "Common": {
      "close": "Fechar",
      "firebase_admin_env_error": "Erro Crítico: Variáveis de ambiente do Firebase Admin não foram encontradas. Verifique seu .env.local",
      "logo_title": "Logo Buckify",
      "select_month": "Selecionar Mês"
    },
    "Navigation": {
      "add_category": "Nova Categoria",
      "add_expense": "Novo Gasto",
      "cards": "Cartões",
      "home": "Início",
      "profile": "Perfil",
      "read_with_ai": "Ler com IA",
      "stats": "Estatísticas"
    },
    "Transactions": {
      "add_expense": "Adicionar Despesa",
      "amount": "Valor (€)",
      "amount_min": "O valor deve ser maior que 0.",
      "amount_placeholder": "0.00",
      "available": "disp.",
      "budget": "Orçamento",
      "categories": {
        "casa": "Casa",
        "mercado": "Mercado",
        "outros": "Outros",
        "restaurantes": "Restaurantes & Lazer",
        "saude": "Saúde & Cuidados",
        "transporte": "Transporte"
      },
      "category": "Categoria",
      "click_to_upload": "Clique para enviar",
      "currency_symbol": "€",
      "date": "Data",
      "date_required": "A data é obrigatória.",
      "description": "Descrição",
      "description_min_length": "A descrição deve ter pelo menos 2 caracteres.",
      "error_parsing_statement": "Erro ao analisar extrato",
      "error_saving": "Erro ao salvar: {message}",
      "error_saving_transactions": "Erro ao salvar transações",
      "example_dinner": "Ex: Jantar fora",
      "expense_added_success": "Despesa adicionada com sucesso!",
      "file_too_large": "Arquivo muito grande (Máx 4MB)",
      "hidden_categories": "+ {count} outras categorias ocultas nas sombras...",
      "logout": "Sair",
      "month_summary": "Resumo do Mês",
      "new_expense": "Nova Despesa",
      "reading_transactions": "Lendo transações...",
      "remaining": "Restante",
      "remaining_label": "Restante:",
      "saving": "Salvando...",
      "select": "Selecione",
      "select_category": "Selecione uma categoria.",
      "session_error_reload": "Erro de sessão. Recarregue a página.",
      "spent": "gastos",
      "supported_formats": "PDF ou Imagem (JPG, PNG)",
      "total_spent": "Gasto Total",
      "transactions_found": "{count} transações encontradas!"
    }
  }
}

export default Resources;
